all:
	g++ -std=c++11 -arch x86_64 -framework OpenGL -I/usr/local/include -L/usr/local/lib GlGeomSphere.cpp GlShaderMgr.cpp GlslWaves.cpp LinearR3.cpp LinearR4.cpp BufferInterface.cpp -lglfw.3.2 -lGLEW.2.1.0
